build:
  version: "3.0"

accounts:
  message: "Welcome to Bank accounts related local APIs "
  contactDetails:
    name: "Moksh Mangal - Developer"
    email: "mm@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345